"""add archived column

Revision ID: c010b772e8e8
Revises: 
Create Date: 2025-03-14 18:04:53.666559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c010b772e8e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Days_of_week', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('Created_at')
        batch_op.drop_column('Days_of_week')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
